### ISSUE TITLE
[Question] Removing dependence on word sequence when going from training to inference

### ISSUE THREAD

**Issue by PavlosMelissinos** [oarriaga/neural_image_captioning#1]
So you need two inputs in order to train a captioning system, what approach did you follow to remove the dependence on ground truth caption priors during inference?

**Comment by oarriaga** [comment]
Hello @PavlosMelissinos 
Yes inference procedure takes two inputs: the <start> token and the image feature vector. By ground truth caption priors, what are you specifically referring to?. The model "initializes" the hidden state of the RNN with the feature vectors of the image; consequently, this could be regarded as the prior information for the model.

**Comment by PavlosMelissinos** [comment]
Nevermind that, it was just poor wording.

During training, at each timestep the RNN receives the feature vectors of the image and a sequence of tokens (words), eg the concatenation of predictions/targets from previous timesteps, in order to predict the next token.

During inference however, the ground truth of the sequence of tokens is not available and the feature vectors of the image should be the only input (along with a <START> token to jump start the prediction process ).

**Comment by oarriaga** [comment]
Yes, the inference procedure puts the initial image and the start token zero padded for all the dimensions in the RNN. Then it takes the prediction given in that step and modifies the zero padded input to include the one-hot encoding of the predicted word. It repeats this process until a <end> token is sampled from the RNN.

**Comment by PavlosMelissinos** [comment]
Oh, so generator.flow yields a whole caption every time, not each timestep separately...

And then you use Masking to ignore the extra timesteps and TimeDistributed to take the remaining of the 32 timesteps one at a time.

Also, for MAX_TOKEN_LENGTH = 32, each time model.predict is called within the for loop in  evaluator.py, it generates predictions for every one of the 32 positions or what remains of them, starting from the current token index. 

So for instance it might go like so (actual example):
```
step 0: [  2,  0,   0,   0,   0,   0, ...,   0,   0,   0] (start token)
step 1: [  3,  3,   3,   3,   3,   3, ...,   3,   3,   3] ('a')
step 2: [  3, 18,  18,  18,  18,  18, ...,  18,  18,  18] ('blue')
step 3: [  3, 18, 158, 158, 158, 158, ..., 158, 158, 158] ('train')
...etc
```
Is this a result of masking?

**Comment by oarriaga** [comment]
Yes exactly it generates a whole caption every time, yes is the masking layer.

**Comment by PavlosMelissinos** [comment]
Great, thanks a lot!
